language: java
jdk:
- oraclejdk8
script:
  mvn clean install -Dnone -P aes,entitydb,freemarker,genson,hsqldb,javascript,jetty-http-client,memcache,mongodb,ossrh,python,redis,tea,undertow
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: pzQFP6DtYLDAiocCHuFxeCSEbcwdBFE5al0LWmobYVJJRRBF/JqFYqc5fCItD5csnu50UOcG1ZJEEfMU8q+7zqrj17A+h7HHsuCmrtWBFR7v8jOvgl2tlwGP9ucCcnZk4Qw+X4gIi/0bX7Q4Ic7m+9KyU+ljFmzQP9RSyH+ZUnl24OEr8h7+JsbK/wMTQtEg55h7U/QbgjXD5FuJEXOtqeh5DXBC3cYF8RJ5iVCRQR1hh+phNKq8h0UddtT8a0ucohpr3zL0Nimwy287X0gpD4tg+eiGLToDOFMk3eRWE+VT13Sy6K3qZhP/ztgjlbDd9pkKcgPOeP1vezXONLhfmKn5K2b0u6wKkxf9PNsqmwnbCKV7a1dpTbXwki7y1AaiPGI4CHL183qS2hkHT1yIPb8kUkHVxBNftrpOKHVNwT6Y2Z9iTspd5bLOfs5P/s98iRWa/aIpNXBLqWTM7SMzmDRfXMoHA9OCXMVCIzkCtVAo1Qgekg1Ulj73KxcVO06AtpEpBjOC085QWITm2FlZfENAnJpSQPCiLl4InK0lF6dZdn16WorCIicUFQHi7m3Jpn8KaTqwDahovd/4/vNHc6rdXFkxVxP6/DdfkWfg81SjKAJixtlCz34S9fovdrEfqiJoizyK5mW783NPhOIkxG/jYvJ1YRF50Gq/N7tKVjs=
  app: fatjar-travis
  on:
    repo: canmogol/FatJar
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/89488db22adfd69fd0a4
    on_success: always  
    on_failure: always 
    on_start: never     # options: [always|never|change]
